### ISSUE TITLE
Simpler circuit and 32/48 KB option modification.

### ISSUE THREAD

**Issue by zxMarce** [nickbild/aqua#1]
Hi Nick!

Recently acquired an Aquarius and started combing the web looking for expansions and cool gadgets for it.

While I have no doubt your design does work, I came with what I think maybe both a simplification and enhancement once I laid on paper and worked out the logic states in your schematic.

Instead of using three chips for decoding, I'd use a single [74LS138](https://www.ti.com/lit/ds/symlink/sn74ls138.pdf) wired as follows:

- Inputs A and B (pins 1, 2) connect to A14, A15 respectively.
- Input C (pin 3) to GND.
- Input -G2a (pin 4) and -G2b (pin 5) to -MREQ.
- Input G1 (pin 6) to +5V.
- Output Y1 (pin 14) to the cathode (negative) of an 1N4148.
- Output Y2 (pin 13) to the cathode (negative) of an 1N4148.
- The anodes of the 1N4148 are connected together and go to -CS on the RAM, with a 4.7K pullup.

The above should work as your current diagram. Half a 74LS139 may also be used, but I have more '138s than '139s, hehehe.
But wait! There's more! With just another 1N4148, a jumper, and a 64KB instead of the 32KB SRAM you can get a fully selectable 32/48KB expansion:

- Output Y3 (pin 12) to the cathode (negative) of a third 1N4148.
- Anode of this third 1N4148, to a two-pin jumper pin
- The other pin of the two-pin jumper to the other anodes, pullup and -CS on the RAM.

An ASCII schematic:

```
                   +5V
                    |
                    <
               4.7K >
                    <
    --+  1N4148     |
    14|----|<|------+----> to RAM -CS pin
      |             |
    13|----|<|------+
      |             |
    12|----|<|--o o-+
    --+         J1     <-- J1 open for 32K, closed for 48K.
LS138
```

As wired, the 74LS138 will enable (make low) output Y0 in the 0x0000-0x3FFF memory range (never should be used), output Y1 in the 0x4000-0x7FFF range, output Y2 in the 0x8000-0xBFFF range, and output Y3 in the 0xC000-0xFFFF (each output corresponding to a 16K "slot").
The diodes and pullup resistor form a '_cheapo OR-gate_', thus when any of Y1, Y2 (or Y3) are active (low), the corresponding diode is forward-biased and drives the output low, enabling the RAM.

Disclaimer: Please note that I do not know if the upper 16KB is actually usable by the Aquarius, as I have z-e-r-o experience with it so far, but I do know it has some kind of "hardware encryption" for cartridge ROMs in this area. Anyway, I read somewhere that this encryption works both ways (read/write), so for RAM it should be "transparent".

Further, the board can use two RAM footprints (one for 32K and another for 64K devices), the jumper between the anode of the third diode (the one connected to Y3) and the pullup resistor in order to have one board fit both RAM sizes.

Regards,
zxMarce.

**Comment by nickbild** [comment]
There are lots of ways to accomplish this same goal, so by all means use the parts you have on hand (that's what I did!).

Thanks for sharing.  Maybe that will help someone else in the future.
